# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-19 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_in', models.CharField(max_length=200, verbose_name='Código del Investigador')),
                ('in_ced', models.CharField(max_length=200, verbose_name='Número de Cédula')),
                ('in_nom', models.CharField(max_length=200, verbose_name='Nombres')),
                ('in_ape', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('in_act', models.BooleanField(verbose_name='¿Se encuentra activo?')),
                ('in_pro', models.ManyToManyField(to='registro.Proyecto')),
            ],
        ),
        migrations.RemoveField(
            model_name='analista',
            name='ana_pro',
        ),
        migrations.DeleteModel(
            name='Analista',
        ),
    ]
