# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-20 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180419_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='even_site',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Lugar del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='even_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='lib_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='revista',
            name='rev_url',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
    ]
